name: Rancher VXLAN - USER
description: |
  Rancher Networking plugin using VXLAN overlay. USER
version: v0.0.1
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos'
