version: '2'
services:
  vxlan:
    cap_add:
    - NET_ADMIN
    image: leodotcloud/net:dev
    network_mode: vxlan
    environment:
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
    command: start-vxlan.sh
    ports:
    - 4789:4789/udp
    # Force cni-driver to start first
    volumes_from:
    - cni-driver
    labels:
      io.rancher.sidekicks: cni-driver
      io.rancher.scheduler.global: 'true'
      io.rancher.cni.link_mtu_overhead: '0'
      io.rancher.service.selector.link: globalvxlan=true
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  cni-driver:
    privileged: true
    image: leodotcloud/net:dev
    command: sh -c "touch /var/log/rancher-cni.log && exec tail ---disable-inotify -F /var/log/rancher-cni.log"
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'rancher-bridge'
      io.rancher.container.dns: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
